version: '3'
services:
  db:
    container_name: mysql
    image: mysql:8.0
    restart: always
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: security_db
    cap_add:
      - SYS_NICE  # mbind 오류 로그 무시

  backend:
    container_name: backend
    image: yellowsunn/security-project-backend 
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    container_name: frontend
    image: yellowsunn/security-project-frontend
    restart: always
    environment:
      VUE_APP_API_DOMAIN: localhost:8080
    ports:
      - "3000:80"

    