spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/study/IdeaProjects/spring_security/security
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

  # 파일 업로드 용량
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB

logging.level:
  org.hibernate:
    SQL: debug
    type: trace

# 사용자 설정
file.upload.directory: ./upload/image/
