spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/study/IdeaProjects/spring_security/security
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true


logging.level:
  org.hibernate:
    SQL: debug
    type: trace
